# Generated by Django 5.0.6 on 2024-06-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0005_alter_category_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_descriptions', to='shop.category')),
            ],
        ),
    ]
