# Generated by Django 5.0.6 on 2024-06-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='shop.catalog'),
        ),
    ]
